cwl_league_names = ["bronze iii",
                    "bronze ii",
                    "bronze i",
                    "silver iii",
                    "silver ii",
                    "silver i",
                    "gold iii",
                    "gold ii",
                    "gold i",
                    "crystal iii",
                    "crystal ii",
                    "crystal i",
                    "master iii", "masters iii",
                    "master ii", "masters ii",
                    "master i", "masters i",
                    "champion iii", "champions iii", "champs iii",
                    "champion ii", "champions ii", "champs ii",
                    "champion i", "champions i", "champs i",
                    ]

cwl_league_order = ["Bronze III",
                    "Bronze II",
                    "Bronze I",
                    "Silver III",
                    "Silver II",
                    "Silver I",
                    "Gold III",
                    "Gold II",
                    "Gold I",
                    "Crystal III",
                    "Crystal II",
                    "Crystal I",
                    "Master III",
                    "Master II",
                    "Master I",
                    "Champion III",
                    "Champion II",
                    "Champion I",
                    ]

trophy_leagues = ["Bronze III",
                  "Bronze II",
                  "Bronze I",
                  "Silver III",
                  "Silver II",
                  "Silver I",
                  "Gold III",
                  "Gold II",
                  "Gold I",
                  "Crystal III",
                  "Crystal II",
                  "Crystal I",
                  "Master III",
                  "Master II",
                  "Master I",
                  "Champion III",
                  "Champion II",
                  "Champion I",
                  ]

answers = {
    1: "pumpkin bomb",
    4: "goblinstoppers",
    6: "[--rough--]",
    7: "heinz",
    9: "gdfechba",
    11: "16",
    13: "qvpgqluq",
    15: "bgiloquv"
}
