cwl_league_names = [
    "bronze iii",
    "bronze ii",
    "bronze i",
    "silver iii",
    "silver ii",
    "silver i",
    "gold iii",
    "gold ii",
    "gold i",
    "crystal iii",
    "crystal ii",
    "crystal i",
    "master iii", "masters iii",
    "master ii", "masters ii",
    "master i", "masters i",
    "champion iii", "champions iii", "champs iii",
    "champion ii", "champions ii", "champs ii",
    "champion i", "champions i", "champs i",
]

cwl_league_order = [
    "Bronze III",
    "Bronze II",
    "Bronze I",
    "Silver III",
    "Silver II",
    "Silver I",
    "Gold III",
    "Gold II",
    "Gold I",
    "Crystal III",
    "Crystal II",
    "Crystal I",
    "Master III",
    "Master II",
    "Master I",
    "Champion III",
    "Champion II",
    "Champion I",
]

trophy_leagues = [
    "Bronze III",
    "Bronze II",
    "Bronze I",
    "Silver III",
    "Silver II",
    "Silver I",
    "Gold III",
    "Gold II",
    "Gold I",
    "Crystal III",
    "Crystal II",
    "Crystal I",
    "Master III",
    "Master II",
    "Master I",
    "Champion III",
    "Champion II",
    "Champion I",
]

veri_status = {
    0: "has not been addressed",
    1: "is awaiting a scout",
    2: "is currently being scouted",
    3: "is awaiting the post-scout survey",
    4: "is awaiting a decision by Council",
}

class_values = {
    1: "comp",
    2: "social",
    3: "gen",
    4: "warFarm",
}

class_names = {
    1: "Competitive",
    2: "Social",
    3: "General",
    4: "War Farming",
}

log_types = {
    "discord_check": 1,
    "pfp": 2,
    "no_clan": 3,
    "danger": 4,
    "rcslist": 5,
    "leader_change": 6,
    "loc_check": 7,
}

league_badges = [
    "https://api-assets.clashofclans.com/badges/200/N5MK3JwQAz0ykmo9EBP5DYU1oplUEc0iVTDo1vzC5vI.png",
    "https://api-assets.clashofclans.com/badges/200/s4LVlJNXHQhft0XANMh9yoTqwU1QTn1MwO5mgSF1MOY.png",
    "https://api-assets.clashofclans.com/badges/200/sy3Hd1Au-NdPNpXdZNxBtDVFoKYYbmK_51n5DZDbl1Q.png",
    "https://api-assets.clashofclans.com/badges/200/h8Hj8FDhK2b1PdkwF7fEbTGY5UkT_lntLEOXbiLTujQ.png",
    "https://api-assets.clashofclans.com/badges/200/QEJMwJrbqBcV7HuE5wifdm8lsNuCwCJXaDGZWpky19E.png",
    "https://api-assets.clashofclans.com/badges/200/nVh-07ETPZDWdh_1WOI1aAEl15Ofh4-fijkcewL44Tg.png",
    "https://api-assets.clashofclans.com/badges/200/i83bbRoM1zBVoSyvYnZdbl1vtHHVa7sBX76zL2aagTU.png",
    "https://api-assets.clashofclans.com/badges/200/fhsMdYytOBaIETKqNukSHiRbzodlgZvYApour-hwm-8.png",
    "https://api-assets.clashofclans.com/badges/200/GZXM36LQ4rQaLngY0gAmQLinOpykdLQZN-1O9_0O9WQ.png",
    "https://api-assets.clashofclans.com/badges/200/rd4V-6Alo06A_qHyMHle8m5lHYl1TeuGM6y0tj1p2BM.png",
    "https://api-assets.clashofclans.com/badges/200/-3znbuN6vMNcXWNznDLSPXSdc82PC0ZC7KxjQLtgsfU.png",
    "https://api-assets.clashofclans.com/badges/200/6DbwmAq6G2Sm3rcMjfIc1SSg1M95_Gj7NiytwQyVKYE.png",
    "https://api-assets.clashofclans.com/badges/200/gN85G3WLOhTa_8M5JBFTufu8jB7V1GyDItWmsCcCSvQ.png",
    "https://api-assets.clashofclans.com/badges/200/1GQUEau_vdCXUD3aQ7iQFX0WWzmwBoq7Xzap3NVPtxs.png",
    "https://api-assets.clashofclans.com/badges/200/7xhfzISLRgeWIbEpZLe91gOR57SRaG8fjGpY5JJ8bXg.png",
    "https://api-assets.clashofclans.com/badges/200/DJrlVIXcle_JuYoqNmiYsOFiRf33gVkVR7ALkLEmgoU.png",
    "https://api-assets.clashofclans.com/badges/200/KGlI-aKixjWRV6pDrimCtcr-fgcjGmx5s1PI3mbbbkc.png",
    "https://api-assets.clashofclans.com/badges/200/pcOtLLm4zUhL3INKyoL6mxHPLdxSoaCCpSolSGdefaM.png",
    "https://api-assets.clashofclans.com/badges/200/XmpfCwaF5emfSxU2VL2OTxi34Zn3Bla8_W9HmcYIKmE.png",
    "https://api-assets.clashofclans.com/badges/200/CIMzTjoH2mpa6lXkV-vI51APuq_n1q549JFat7uTTro.png",
    "https://api-assets.clashofclans.com/badges/200/9fDPEA5GFjXbC0-xXMtJsfzjUE0cGF051B7gqBW6FWI.png",
    "https://api-assets.clashofclans.com/badges/200/vzzebrfiBc8-sctQ_pyYqTMnaHVbw1eg9LP7PusBbks.png",
    "https://api-assets.clashofclans.com/badges/200/T1VJQX5AbBcBxaK9xJ6MZwisLDhMcmbhMh8Nbdl0q0w.png",
    "https://api-assets.clashofclans.com/badges/200/z0lQQHgrILAY-888t6d0PsamKs8xX8NmTOK9JMunyeM.png",
    "https://api-assets.clashofclans.com/badges/200/TshA1kYR_8QfTrOvl04EHusbwaBVMWSjs-pHncZOVNU.png",
    "https://api-assets.clashofclans.com/badges/200/8WhutCWKrbciJps9ktkcdEoYIo0QLnFN3AHPnpGP0hA.png",
    "https://api-assets.clashofclans.com/badges/200/fGKQ6xGxA2WNvAs4nyeDHKdfaPlkEpuN2lvUM4Tk1fI.png",
    "https://api-assets.clashofclans.com/badges/200/D-4pENmc5xSGPU2KWtJBa7dSjHj3hX42uLDUQ4zWPIo.png",
    "https://api-assets.clashofclans.com/badges/200/iqjv-Qs27PRHRZqwfVY_zpdCfI8A3cP85eSNimU8sTA.png",
    "https://api-assets.clashofclans.com/badges/200/7oKk8-NNowB8iEtrAF5iWPby34Kn_F7353sRRdZpyZM.png",
    "https://api-assets.clashofclans.com/badges/200/lZNEVmm2zgQtmP4CCHqVMHEUHbDlPCFizQiYe5s_KQM.png",
    "https://api-assets.clashofclans.com/badges/200/p4X6ZuNfAZ_ENKJOhy2u8og4UJJcKNYwuhr8TQkQ9Is.png",
    "https://api-assets.clashofclans.com/badges/200/jYTDcpB5NHkRf2_eVj9uuDwIAAOPyuPWbusUXin7uEo.png",
    "https://api-assets.clashofclans.com/badges/200/gF1wdSrH72cPmAc9LG41nRZoUdI1apsF0ZxxEXtxVoA.png",
    "https://api-assets.clashofclans.com/badges/200/YZEZ1nt3aCeu0EyoEj4eGWQgu7YYQfk0JeKS8TpGrug.png",
    "https://api-assets.clashofclans.com/badges/200/VFsOK1xnVLt2fZp90dhmFSxZ53CLeKmeCe-AqBIPmiM.png",
    "https://api-assets.clashofclans.com/badges/200/U3cfL9RayYC2QQVjLy7A1jm7Q5HBWNWdaKO5mc8TzJg.png",
    "https://api-assets.clashofclans.com/badges/200/_BlteI9b1K9-s78UHBiZWUHrxhMReOXmBt_QWpZXNU4.png",
    "https://api-assets.clashofclans.com/badges/200/g3mEo_dNQSQaOgWko8nNf6jPW1sjxLnjSRS2Dk4fWNo.png",
    "https://api-assets.clashofclans.com/badges/200/s9_rjBN-oJ4_lpG6fp42zVFHrPt4V_iyn8VJ_J96xpE.png",
    "https://api-assets.clashofclans.com/badges/200/gkfmKR3V-ZbgSidmr7p5nlrHQO3LM4tzUMoBD0CGJpA.png",
    "https://api-assets.clashofclans.com/badges/200/5SeqPcn_LqM4Y04mPuciJXWyqHn5SSAcgxWvc7tvEvY.png",
    "https://api-assets.clashofclans.com/badges/200/dYKk_W5b8tS8mWBzUV_vuVfXIdBGoXszLrq9x8fB3jA.png",
    "https://api-assets.clashofclans.com/badges/200/5SeqPcn_LqM4Y04mPuciJXWyqHn5SSAcgxWvc7tvEvY.png",
    "https://api-assets.clashofclans.com/badges/200/thXuucdocdtfUts55bsAoGfQ0P8ghwLezzeG-UUajp0.png",
    "https://api-assets.clashofclans.com/badges/200/hnUFo_38Tf4n8-C8k8XX-8Nn8_KNPSacT89Y_8m0SRU.png",
    "https://api-assets.clashofclans.com/badges/200/Uv-gmJrJHNTwweMUMk3cb-kgf6Ve5l_8gENUxTQM2HY.png",
    "https://api-assets.clashofclans.com/badges/200/V9EFxkaQ0GfKonWyn3gjimsnAMh3SPXFQeIkpKnNP7Y.png",
    "https://api-assets.clashofclans.com/badges/200/2avGGTGMjQ_nxnE5ZZlB6Xk6ujYkm91o7uCqEx37Ox0.png",
    "https://api-assets.clashofclans.com/badges/200/rwWdCGtSEiV8PdSMWFx1zjkfT9-nQYBBss5y0j1bTzM.png",
    "https://api-assets.clashofclans.com/badges/200/Hl0g6w-hr3qsiX_mAl9YDtgB8UksV_5KsVKgYBTyERE.png",
    "https://api-assets.clashofclans.com/badges/200/dBujq3w_K8rfIWMXVnoECFjrXpyZ9FPeCLGXOGmfczA.png",
    "https://api-assets.clashofclans.com/badges/200/_cdaxnR9DhJfUY-0ptAooMzsj6VrKxnSZxRDx_KFWAc.png",
    "https://api-assets.clashofclans.com/badges/200/uFuGQyWEaz5wiffYOEY9EPjSXZk1VBmyqEN3ClACjO0.png",
    "https://api-assets.clashofclans.com/badges/200/cDGb44uVx9D1IglE5vj0pRcPnvSf-WwIwy5oE4yXb44.png",
    "https://api-assets.clashofclans.com/badges/200/KBtwIToS85C-c3ROYqXdkB7DkmMY4zUP3BjJ8IDK1Qw.png",
    "https://api-assets.clashofclans.com/badges/200/Yrd9aOK78-xnYjDIb-D2gLzEP5_BpvNLDM6P5bp7Dfc.png",
    "https://api-assets.clashofclans.com/badges/200/EuwRqrD9Pz0OUjlHW-_JMQswZJa51vhHnSTGvX6WWHg.png",
    "https://api-assets.clashofclans.com/badges/200/SWbnIR_7T4HHtT2li0SzBeB5qFs7PAW2BToeOifJ3n0.png",
    "https://api-assets.clashofclans.com/badges/200/gJoboXW6seHlcO2FMKrz4ySoJzUoiDDAYOuUycp369w.png",
    "https://api-assets.clashofclans.com/badges/200/PFufY610p6gFjN4APhPDEVorwo6GNCH1fNZIJWZAQpE.png",
]
